version: "3"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: kinto/kinto-server:latest
    depends_on:
    - db
    ports:
    - "127.0.0.1:8888:8888"
    volumes:
    - ./config:/etc/kinto
